world.server.onlyadmin=false
world.server.scriptspath=scripts
world.server.scriptspath2=scripts_custom
world.server.cachescript=false
login.server.minor=3
login.server.name=新楓之谷
login.server.eventmessage=
login.server.message=享受游戲，熱愛生活
login.server.flag=0
login.server.status=2
login.server.userlimit=10
login.server.defaultuserlimit=0
world.autoregister=true
world.bangainexp=false
world.bantrade=false
world.bandropitem=false
world.disablepotential=false
world.equipcheckfame=false
server.verifydamage=false
world.defaultcuttable=-1
world.halloweenskin=false
world.christmasskin=false
login.server.port=8484
cash.server.port=8787
chat.server.port=8283
auction.server.port=8700
channel.server.ports=5
channel.rate.baseexp=100

channel.rate.exp=500
channel.rate.meso=1
channel.rate.drop=1

channel.rate.globaldrop=1
channel.rate.trait=1
channel.rate.potentiallevel=1
channel.player.maxap=30000
channel.player.maxhp=500000
channel.player.maxmp=500000
channel.player.maxlevel=300
channel.player.maxmeso=99999999999
channel.player.damageLimit=10000000000
channel.player.beginnermap=10000
channel.player.maxcharacters=6
channel.player.resufreecount=5
channel.player.autocompletequest=false
channel.player.disablecooldown=false
world.refreshtime=0
world.refreshrank=120
world.autoban=true
world.blockskills=
world.closejobs=
world.hidenpcs={}
channel.server.openpvp=false
channel.server.pvpmaps=910000018
channel.server.chalkboard=false
channel.server.createguildcost=5000000
channel.server.enablepointsbuy=true
channel.server.applyplayerdebuff=false
channel.server.applymonsterstatus=false
channel.server.events=BossZakum_CHAOS,BossZakum_EASY,BossZakum_NORMAL,ChaosZakum
channel.monster.refresh=7
channel.monster.elitecount=500



#db.ip=localhost
#db.port=3306
#db.name=playms
#db.user=root
#db.password=123456

db.ip=127.0.0.1
db.port=3306
db.user=root
db.password=QqAa123456
db.name=tms245


check.cheatitemexcludes=
pet.defaultflag=7807
channel.chaosch=2,3,4,5,6,7,8,9,10,11,12,13,14,15
channel.abnormalch=16
channel.mvpch.bronze=17,18
channel.mvpch.silver=19,20,21,22,23,24
channel.mvpch.gold=25,26,27,28
channel.mvpch.diamond=29
channel.mvpch.red=30
channel.chaos.baseexp=200
channel.abnormal.baseexp=250
channel.mvpch.bronze.baseexp=200
channel.mvpch.silver.baseexp=300
channel.mvpch.gold.baseexp=400
channel.mvpch.diamond.baseexp=500
channel.mvpch.red.baseexp=600
channel.chaos.meso=110
channel.abnormal.meso=135
channel.mvpch.bronze.meso=125
channel.mvpch.silver.meso=150
channel.mvpch.gold.meso=185
channel.mvpch.diamond.meso=250
channel.mvpch.red.meso=300
mvp.amount.rate=1.0
familiar.sealcost=200
world.limitednames=royalFace,animaOn
starforce.maplepoint.amount=9
starforce.maplepointsafe.amount=50
starforce.curse.enable=true
map.maxburningfieldstep=10
inventory.cancutitems=
inventory.accshareitems=
tespia=false
testpia.multiplayer=false
map.effect=0
inventory.itemmaxslot={}
world.createcharburning=0
world.createcharburningdays=7
noEncryptHosts=
mobPointMinLv=150
ptyPointModifier=1
mileageDailyLimitMax=100
mileageMonthlyLimitMax=500
mileageAsMaplePoint=false
partyQuestRevive=false
mobPointNeedPickup=true
world.player.enablerebornbuff=false
familiarIncDAMrHard=false
goldenAppleFragmentNoTimeLimit=false
KMS_NirvanaFlameTier=true
channel.server.dojoMobMaxHpR=100
channel.server.dojoMobAtkR=100
channel.server.dojoMobDefenseRateR=100
HideBulbQuest=false
BlockChairs=
defaultDamageSkinSlot=30
min_donate=100
TeachCost=0,0,0,0,5000000,6000000,7000000,8000000,9000000,10000000
map.rune.close=false
defaultMeso=true
cash.cashshoppack=
cash.pbtapreward1=
cash.pbtapreward2=
cash.pbtapreward3=
Fishing.Enable=true
Fishing.Check.MAP=749050500,749050501,749050502,970020000,970020005
Fishing.Check.Chair=true
Fishing.Chair=3011000
Fishing.Time=60000
Fishing.Time.Vip=30000
Fishing.Time.GM=10000
Fishing.Chance=70
Fishing.Chance.Vip=90
Fishing.Chance.GM=100
server.benulite.C=10
server.benulite.B=10
server.benulite.A=10
server.benulite.S=10
game.cube.mrate=25
game.cube.lrate=1
ecpay.ip=
ecpay.port=8080
ecpay.merchantid=
ecpay.hashkey=
ecpay.hashiv=
ecpay.url=
wzpath=.\\wz
server.host=127.0.0.1
server.updatePlayerInGUI=false
gui.enabled=true
gm.forall=true

# 跳過的ops
sendops=LP_AliveReq,LP_MobCtrlAck,LP_SummonedMove,LP_NpcController,LP_FieldNpcEnter,LP_NpcMove
recvops=CP_AliveAck,CP_WvsSetUpStep,CP_WAIT_FOR_LOAD_FILE_LIST,CP_MobMove,CP_UserMove,CP_NpcMove,CP_AndroidMove
